export const USER_MESSAGE = {
  VALIDATION_ERROR: 'Lỗi dữ liệu đầu vào',
  DISPLAY_NAME_IS_REQUIRED: 'Không được bỏ trống tên hiển thị',
  DISPLAY_NAME_MUST_BE_A_STRING: 'Tên hiển thị phải là một chuỗi ký tự',
  DISPLAY_NAME_LENGTH_MUST_BE_FROM_1_TO_50: 'Tên hiển thị phải có độ dài từ 2 đến 50 ký tự',
  EMAIL_IS_REQUIRED: 'Không được bỏ trống địa chỉ email',
  EMAIL_IS_NOT_VALID: 'Địa chỉ email không hợp lệ',
  EMAIL_IS_MUST_BE_A_STRING: 'Địa chỉ email phải là một chuỗi ký tự',
  EMAIL_LENGTH_MUST_BE_FROM_5_TO_100: 'Địa chỉ email phải có độ dài từ 5 đến 100 ký tự',
  EMAIL_IS_ALWAYS_EXISTENT: 'Địa chỉ email đã được sử dụng',
  PHONE_IS_REQUIRED: 'Không được bỏ trống số điện thoại',
  PHONE_IS_NOT_VALID: 'Số điện thoại không hợp lệ',
  PHONE_MUST_BE_A_STRING: 'Số điện thoại phải là một chuỗi ký tự',
  PHONE_LENGTH_MUST_BE_FROM_10_TO_11: 'Số điện thoại phải có độ dài từ 10 đến 11 ký tự',
  PHONE_IS_ALWAYS_EXISTENT: 'Số điện thoại đã được sử dụng',
  PASSWORD_IS_REQUIRED: 'Không được bỏ trống mật khẩu',
  PASSWORD_MUST_BE_A_STRING: 'Mật khẩu phải là một chuỗi ký tự',
  PASSOWRD_LENGTH_MUST_BE_FROM_8_TO_100: 'Mật khẩu phải có độ dài từ 8 đến 100 ký tự',
  PASSOWRD_MUST_BE_STRONG: 'Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt',
  COMFIRM_PASSWORD_IS_REQUIRED: 'Không được bỏ trống xác nhận mật khẩu',
  COMFIRM_PASSWORD_MUST_BE_A_STRING: 'Xác nhận mật khẩu phải là một chuỗi ký tự',
  COMFIRM_PASSWORD_LENGTH_MUST_BE_FROM_8_TO_100: 'Xác nhận mật khẩu phải có độ dài từ 8 đến 100 ký tự',
  COMFORM_PASSWORD_MUST_BE_STRONG:
    'Xác nhận mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt',
  COMFIRM_PASSWORD_MUST_BE_THE_SAME_AS_PASSWORD: 'Xác nhận mật khẩu phải trùng khớp với mật khẩu',
  REGISTER_SUCCESS: 'Đăng ký thành công! Vui lòng đăng nhập lại',
  REGISTER_FAILURE: 'Đăng ký thất bại',
  INCORRECT_EMAIL_OR_PASSWORD: 'Email hoặc mật khẩu không chính xác',
  LOGIN_SUCCESS: 'Đăng nhập thành công!',
  LOGIN_FAILURE: 'Đăng nhập thất bại',
  AUTHORIZATION_IS_REQUESTED: 'Chức năng này yêu cầu gửi Access token',
  AUTHORIZATION_MUST_BE_A_STRING: 'Access token phải là một chuỗi ký tự',
  AUTHORIZATION_INVALID: 'Access token không hợp lệ',
  REFUSED_TOKEN_IS_REQUESTED: 'Chức năng này yêu cầu gửi Refresh token',
  REFUSED_TOKEN_MUST_BE_A_STRING: 'Refresh token phải là một chuỗi ký tự',
  REFRESH_TOKEN_DOES_NOT_EXIST: 'Refresh token không tồn tại',
  REFRESH_TOKEN_INVALID: 'Refresh token không hợp lệ',
  LOGOUT_SUCCESS: 'Đăng xuất thành công!',
  LOGOUT_FAILURE: 'Đăng xuất thất bại',
  EMAIL_VERIFY_TOKEN_IS_REQUESTED: 'Chức năng này yêu cầu gửi mã xác minh email',
  EMAIL_VERIFY_TOKEN_MUST_BE_A_STRING: 'Mã xác minh email phải là một chuỗi ký tự',
  EMAIL_VERIFY_TOKEN_DOES_NOT_EXIST: 'Mã xác minh email không tồn tại',
  EMAIL_ALREADY_VERIFIED: 'Email đã được xác minh',
  EMAIL_VERIFY_SUSSCESS: 'Xác minh email thành công!',
  EMAIL_ALREADY_SENDING: 'Email đã được gửi, vui lòng kiểm tra hộp thư của bạn',
  EMAIL_VERIFY_CODE_SEND_SUCCESS: 'Mã xác minh email đã được gửi thành công! Vui lòng kiểm tra hộp thư của bạn',
  EMAIL_VERIFY_CODE_SEND_FAILURE: 'Gửi mã xác minh email thất bại',
  EMAIL_VERIFY_CODE_IS_REQUESTED: 'Không được bỏ trống mã xác minh email',
  EMAIL_VERIFY_CODE_MUST_BE_A_STRING: 'Mã xác minh email phải là một chuỗi ký tự',
  EMAIL_VERIFY_CODE_INVALID: 'Mã xác minh email không hợp lệ',
  EMAIL_VERIFY_CODE_HAS_NOT_BEEN_SENT: 'Mã xác minh email chưa được gửi',
  EMAIL_VERIFY_CODE_RESEND_SUCCESS: 'Mã xác minh email đã được gửi lại thành công! Vui lòng kiểm tra hộp thư của bạn',
  EMAIL_VERIFY_CODE_RESEND_FAILURE: 'Gửi lại mã xác minh email thất bại',
  USER_IS_NOT_VERIFIED: 'Bạn phải xác minh email bỏ sử dụng chức năng này',
  USERS_NOT_FOUND: 'Không tìm thấy người dùng với email này',
  FORGOT_PASSWORD_SEND_EMAIL_SUCCESS:
    'Email yêu cầu đặt lại mật khẩu đã được gửi thành công! Vui lòng kiểm tra hộp thư của bạn',
  FORGOT_PASSWORD_SEND_EMAIL_FAILURE: 'Gửi email yêu cầu đặt lại mật khẩu thất bại',
  TOKEN_IS_REQUESTED: 'Mã xác thực thay đổi mật khẩu là bắt buộc',
  TOKEN_MUST_BE_A_STRING: 'Mã xác thực thay đổi mật khẩu phải là một chuỗi ký tự',
  TOKEN_INVALID: 'Mã xác thực thay đổi mật khẩu không hợp lệ',
  CHANGED_PASSWORD_SUCCESS: 'Thay đổi mật khẩu thành công! Vui lòng đăng nhập lại',
  CHANGED_PASSWORD_FAILURE: 'Thay đổi mật khẩu thất bại',
  USER_NOT_FOUND: 'Không tìm thấy người dùng',
  FORGOT_PASSWORD_TOKEN_INVALID: 'Mã xác nhận thay đổi mật khẩu không hợp lệ',
  NEW_PASSWORD_IS_REQUIRED: 'Không được bỏ trống mật khẩu mới',
  NEW_PASSWORD_MUST_BE_A_STRING: 'Mật khẩu mới phải là một chuỗi ký tự',
  NEW_PASSOWRD_LENGTH_MUST_BE_FROM_8_TO_100: 'Mật khẩu mới phải có độ dài từ 8 đến 100 ký tự',
  NEW_PASSOWRD_MUST_BE_STRONG:
    'Mật khẩu mới phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt',
  COMFIRM_NEW_PASSWORD_IS_REQUIRED: 'Không được bỏ trống xác nhận mật khẩu mới',
  COMFIRM_NEW_PASSWORD_MUST_BE_A_STRING: 'Xác nhận mật khẩu mới phải là một chuỗi ký tự',
  COMFIRM_NEW_PASSWORD_LENGTH_MUST_BE_FROM_8_TO_100: 'Xác nhận mật khẩu mới phải có độ dài từ 8 đến 100 ký tự',
  COMFORM_NEW_PASSWORD_MUST_BE_STRONG:
    'Xác nhận mật khẩu mới phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt',
  COMFIRM_NEW_PASSWORD_MUST_BE_THE_SAME_AS_PASSWORD: 'Xác nhận mật khẩu mới phải trùng khớp với mật khẩu mới',
  PASSWORD_INCORRECT: 'Mật khẩu không chính xác',
  NEW_PASSWORD_MUST_BE_DIFFERENT_FROM_OLD_PASSWORD: 'Mật khẩu mới phải khác so với mật khẩu cũ',
  CHANGED_EMAIL_SUCCESS: 'Thay đổi email thành công! Vui lòng đăng nhập lại',
  CHANGED_EMAIL_FAILURE: 'Thay đổi email thất bại',
  CHANGED_PHONE_SUCCESS: 'Thay đổi số điện thoại thành công!',
  CHANGED_PHONE_FAILURE: 'Thay đổi số điện thoại thất bại',
  AVATAR_IS_REQUIRED: 'Bạn phải tải lên ảnh đại diện',
  IMAGE_MUST_BE_3x4_ASPECT_RATIO: 'Ảnh phải có tỷ lệ khung hình 3:4',
  IMAGE_INVALID: 'Tệp ảnh không hợp lệ',
  AVATAR_3X4_MUST_BE_IMAGE: 'Ảnh đại diện phải là tệp ảnh',
  CHANGED_AVATAR_SUCCESS: 'Thay đổi ảnh đại diện thành công!',
  CHANGED_AVATAR_FAILURE: 'Thay đổi ảnh đại diện thất bại',
  USER_IS_TEMPORARY: 'Vui lòng thay đổi mật khẩu tạm thời trước khi đăng nhập',
  CHANGED_TEMPORARY_PASSWORD_SUCCESS: 'Thay đổi mật khẩu tạm thời thành công! Vui lòng đăng nhập lại',
  CHANGED_TEMPORARY_PASSWORD_FAILURE: 'Thay đổi mật khẩu tạm thời thất bại',
  ACCOUNT_IS_NOT_A_CURRENT_ACCOUNT:
    'Tài khoản này không do chúng tôi cấp hoặc tài khoản đã được thay đổi mật khẩu tạm thời',
  NOT_PERMISSION_TODO_THIS: 'BẠN LÀ NGƯỜI DÙNG? CÚT'
} as const

export const AUTHENTICATION_MESSAGE = {
  ACCESS_TOKEN_AND_REFRESH_TOKEN_IS_MISSING: 'Bạn phải đăng nhập bỏ sử dụng chức năng này',
  REFRESH_TOKEN_INVALID: 'Refresh token không hợp lệ',
  NOT_PERMISSION_TODO_THIS: 'Bạn không có quyền thực hiện hành động này'
} as const

export const VEHICLE_MESSGAE = {
  VEHICLE_TYPE_IS_REQUIRED: 'Không được bỏ trống loại xe',
  VEHICLE_TYPE_IS_INVALID: 'Loại xe không hợp lệ',
  VEHICLE_TYPE_MUST_BE_A_NUMBER: 'Loại xe phải là một số',
  SEAT_TYPE_IS_REQUIRED: 'Không được bỏ trống loại ghế',
  SEAT_TYPE_IS_INVALID: 'Loại ghế không hợp lệ',
  SEAT_TYPE_IS_MUST_BE_A_NUMBER: 'Loại ghế phải là một số',
  SEATS_IS_REQUIRED: 'Không được bỏ trống số lượng ghế',
  SEATS_IS_MUST_BE_A_NUMBER: 'Số lượng ghế phải là một số',
  SEATS_IS_MUST_BE_GREATER_THAN_0: 'Số lượng ghế phải lớn hơn 0',
  RULES_IS_REQUIRED: 'Không được bỏ trống quy định trên xe',
  RULES_IS_MUST_BE_A_STRING: 'Quy định trên xe phải là một chuỗi ký tự',
  EMAIL_LENGTH_MUST_BE_FROM_10_TO_2000: 'Quy định trên xe phải có độ dài từ 10 đến 2000 ký tự',
  AMENITIES_IS_REQUIRED: 'Không được bỏ trống tiện nghi trên phương tiện',
  AMENITIES_IS_MUST_BE_A_STRING: 'Tiện nghi trên phương tiện phải là một chuỗi',
  AMENITIES_LENGTH_MUST_BE_FROM_0_TO_500: 'Tiện nghi trên phương tiện phải có độ dài từ 0 đến 500 ký tự',
  LICENSE_PLATE_IS_REQUIRED: 'Không được bỏ trống biển số xe',
  LICENSE_PLATE_IS_MUST_BE_A_STRING: 'Biển số xe phải là một chuỗi ký tự',
  LICENSE_PLATE_LENGTH_MUST_BE_FROM_8_TO_9: 'Biển số xe phải có độ dài từ 8 đến 9 ký tự',
  LICENSE_PLATE_IS_ALREADY_EXISTS: 'Biển số xe đã được đăng ký',
  ONLY_UPLOAD_IMAGES: 'Bạn chỉ có thể tải lên hình ảnh',
  ONLY_UPLOAD_EACH_IMAGE_UP_TO_5MB: 'Mỗi hình ảnh không được lớn hơn 5MB',
  ONLY_UPLOAD_UP_TO_30_IMAGES: 'Bạn có thể tải lên tối đa 30 hình ảnh',
  UPLOAD_FAILED: 'Tải lên thất bại',
  CREATE_VEHICLE_SUCCESS: 'Tạo thông tin phương tiện thành công!',
  CREATE_VEHICLE_FAILURE: 'Tạo thông tin phương tiện thất bại',
  VEHICLE_ID_IS_REQUIRED: 'Không được bỏ trống ID phương tiện',
  VEHICLE_ID_IS_MUST_BE_A_STRING: 'ID phương tiện phải là một chuỗi ký tự',
  VEHICLE_ID_IS_MUST_BE_A_ID: 'ID phương tiện không đúng định dạng',
  VEHICLE_ID_IS_NOT_EXIST: 'ID phương tiện không tồn tại hoặc bạn không có quyền thực hiện điều này',
  DELETE_VEHICLE_SUCCESS: 'Xóa thông tin phương tiện thành công!',
  DELETE_VEHICLE_FAILURE: 'Xóa thông tin phương tiện thất bại',
  GET_VEHICLE_FAILURE: 'Lấy thông tin phương tiện thất bại',
  UPDATE_VEHICLE_SUCCESS: 'Cập nhật thông tin phương tiện thành công!',
  UPDATE_VEHICLE_FAILURE: 'Cập nhật thông tin phương tiện thất bại',
  CURRENT_IS_REQUIRED: 'Không được bỏ trống số trang hiện tại',
  CURRENT_IS_MUST_BE_A_NUMBER: 'Số trang hiện tại phải là một số',
  CURRENT_IS_MUST_BE_GREATER_THAN_0: 'Số trang hiện tại phải lớn hơn 0',
  KEYWORDS_IS_REQUIRED: 'Không được bỏ trống từ khóa',
  NO_MATCHING_RESULTS_FOUND: 'Không tìm thấy kết quả phù hợp',
  DECISION_IS_REQUIRED: 'Không được bỏ trống quyết định',
  DECISION_IS_MUST_BE_A_BOOLEAN: 'Quyết định phải có giá trị true hoặc false',
  USER_NOT_FOUND: 'Không tìm thấy người dùng',
  IMAGE_IS_REQUIRED: 'Phải tải lên ít nhất một hình ảnh của phương tiện',
  CENSOR_VEHICLE_SUCCESS: 'Kiểm duyệt phương tiện thành công!',
  CENSOR_VEHICLE_FAILURE: 'Kiểm duyệt phương tiện thất bại',
  GET_VEHICLE_LIST_FAILURE: 'Lấy danh sách phương tiện thất bại',
  FIND_VEHICLE_FAILURE: 'Tìm kiếm thông tin phương tiện thất bại',
  SESSION_TIME_IS_REQUIRED: 'Không được bỏ trống thời gian của phiên',
  SESSION_TIME_IS_MUST_BE_A_DATE: 'Thời gian phiên không đúng định dạng'
} as const

export const BUSROUTE_MESSAGE = {
  START_POINT_IS_REQUIRED: 'Không được bỏ trống điểm khởi hành',
  START_POINT_LENGTH_MUST_BE_FROM_5_TO_500: 'Điểm khởi hành phải có độ dài từ 5 đến 500 ký tự',
  END_POINT_IS_REQUIRED: 'Không được bỏ trống điểm đến',
  END_POINT_LENGTH_MUST_BE_FROM_5_TO_500: 'Điểm đến phải có độ dài từ 5 đến 500 ký tự',
  START_POINT_AND_END_POINT_MUST_BE_DIFFERENT: 'Điểm khởi hành và điểm đến phải khác nhau',
  DEPARTURE_TIME_IS_REQUIRED: 'Không được bỏ trống thời gian khởi hành',
  DEPARTURE_TIME_MUST_BE_ISO8601: 'Thời gian khởi hành không đúng định dạn',
  ARRIVAL_TIME_IS_REQUIRED: 'Không được bỏ trống thời gian dự kiến đến dích',
  ARRIVAL_TIME_MUST_BE_ISO8601: 'Thời gian dự kiến đến dích không đúng định dạn',
  ARRIVAL_TIME_MUST_BE_GREATER_THAN_DEPARTURE_TIME: 'Thời gian dự kiến đến đích phải muộn hơn thời gian khởi hành',
  PRICE_IS_REQUIRED: 'Không được bỏ trống giá vé',
  PRICE_MUST_BE_A_NUMBER: 'Giá vé phải là một số',
  PRICE_MUST_BE_GREATER_THAN_0: 'Giá vé phải lớn hơn 0',
  QUANTITY_IS_REQUIRED: 'Không được bỏ trống số lượng vé',
  QUANTITY_MUST_BE_A_NUMBER: 'Số lượng vé phải là một số',
  QUANTITY_MUST_BE_GREATER_THAN_0: 'Số lượng vé phải lớn hơn 0',
  QUANTITY_MUST_BE_LESS_THAN_OR_EQUAL_TO_VEHICLE_SEATS: 'Số lượng vé phải nhỏ hơn hoặc bằng số ghế trên xe',
  CREATE_BUS_ROUTE_SUCCESS: 'Thêm thông tin tuyến thành công!',
  CREATE_BUS_ROUTE_FAILURE: 'Thêm thông tin tuyến thất bại',
  BUS_ROUTE_ID_IS_REQUIRED: 'ID tuyến không được bỏ trống',
  BUS_ROUTE_ID_IS_MUST_BE_A_STRING: 'ID tuyến phải là một chuỗi ký tự',
  BUS_ROUTE_ID_IS_MUST_BE_A_ID: 'ID tuyến không đúng định dạng',
  BUS_ROUTE_ID_IS_NOT_EXIST: 'ID tuyến không tồn tại hoặc bạn không có quyền thực hiện điều này',
  UPDATE_BUS_ROUTE_SUCCESS: 'Cập nhật thông tin tuyến thành công!',
  UPDATE_BUS_ROUTE_FAILURE: 'Cập nhật thông tin tuyến thất bại',
  DELETE_BUS_ROUTE_SUCCESS: 'Xóa thông tin tuyến thành công!',
  DELETE_BUS_ROUTE_FAILURE: 'Xóa thông tin tuyến thất bại',
  CURRENT_IS_REQUIRED: 'Không được bỏ trống số trang hiện tại',
  CURRENT_IS_MUST_BE_A_NUMBER: 'Số trang hiện tại phải là một số',
  CURRENT_IS_MUST_BE_GREATER_THAN_0: 'Số trang hiện tại phải lớn hơn 0',
  NO_MATCHING_RESULTS_FOUND: 'Không tìm thấy kết quả phù hợp',
  DEPARTURE_TIME_MUST_BE_GREATER_THAN_NOW: 'Thời gian khởi hành phải muộn hơn thời gian hiện tại',
  ARRIVAL_TIME_MUST_BE_GREATER_THAN_NOW: 'Thời gian dự kiến đến nơi phải muộn hơn thời gian hiện tại',
  PRICE_MUST_BE_LESS_THAN_100000000: 'Giá vé phải nhỏ hơn 100.000.000 VND',
  GET_BUS_ROUTE_FAILED: 'Lấy thông tin tuyến thất bại',
  FIND_BUS_ROUTE_FAILED: 'Tìm kiếm thông tin tuyến thất bại',
  SESSION_TIME_IS_REQUIRED: 'Không được bỏ trống thời gian của phiên',
  SESSION_TIME_IS_MUST_BE_A_DATE: 'Thời gian phiên không đúng định dạng'
} as const

export const ORDER_MESSAGE = {
  BUS_ROUTE_ID_IS_REQUIRED: 'Không được bỏ trống ID tuyến',
  BUS_ROUTE_ID_MUST_BE_STRING: 'ID tuyến phải là một chuỗi ký tự',
  BUS_ROUTE_ID_MUST_BE_MONGO_ID: 'ID tuyến không đúng định dạng',
  BUS_ROUTE_ID_NOT_EXIST: 'ID tuyến không tồn tại',
  NAME_IS_REQUIRED: 'Tên của người đại diện không được bỏ trống',
  NAME_MUST_BE_STRING: 'Tên của người đại diện phải là một chuỗi ký tự',
  NAME_LENGTH_MUST_BE_FROM_1_TO_150: 'Tên của người đại diện phải có độ dài từ 1 đến 150 ký tự',
  PHONE_IS_REQUIRED: 'Số điện thoại của người đại diện không được bỏ trống',
  PHONE_MUST_BE_STRING: 'Số điện thoại của người đại diện phải là một chuỗi ký tự',
  PHONE_LENGTH_MUST_BE_FROM_10_TO_11: 'Số điện thoại của người đại diện phải có độ dài từ 10 đến 11 ký tự',
  PHONE_MUST_BE_MOBILE_PHONE: 'Số điện thoại của người đại diện không đúng định dạn',
  QUANTITY_IS_REQUIRED: 'Không được bỏ trống số lượng vé',
  QUANTITY_MUST_BE_INT: 'Số lượng vé phải là một số nguyên',
  QUANTITY_MUST_BE_GREATER_THAN_0: 'Số lượng vé phải lớn hơn 0',
  QUANTITY_MUST_BE_LESS_THAN_REMAINING_QUANTITY: 'Tuyến này không còn đủ vé theo yêu cầu',
  BALANCE_NOT_ENOUGH: 'Số dư của bạn không đủ bỏ hoàn thành giao dịch này',
  ORDER_SUCCESS: 'Đặt vé thành công!',
  ORDER_FAILURE: 'Đặt vé thất bại',
  CURRENT_IS_REQUIRED: 'Không được bỏ trống số trang hiện tại',
  CURRENT_IS_MUST_BE_A_NUMBER: 'Số trang hiện tại phải là một số',
  CURRENT_IS_MUST_BE_GREATER_THAN_0: 'Số trang hiện tại phải lớn hơn 0',
  NO_MATCHING_RESULTS_FOUND: 'Không tìm thấy kết quả phù hợp',
  ORDER_ID_IS_REQUIRED: 'ID đơn hàng không được bỏ trống',
  ORDER_ID_IS_MUST_BE_A_STRING: 'ID đơn hàng phải là một chuỗi ký tự',
  ORDER_ID_IS_MUST_BE_A_MONGO_ID: 'ID đơn hàng không đúng định dạng',
  ORDER_ID_IS_NOT_EXIST: 'ID đơn hàng không tồn tại',
  QUANTITY_MUST_BE_LESS_THAN_1000: 'Số lượng vé phải nhỏ hơn 1.000',
  TICKET_ID_IS_REQUIRED: 'Không được bỏ trống ID vé',
  TICKET_ID_IS_MUST_BE_A_STRING: 'ID vé phải là một chuỗi ký tự',
  TICKET_ID_IS_MUST_BE_A_MONGO_ID: 'ID vé không đúng định dạng',
  TICKET_ID_IS_NOT_EXIST: 'ID vé không tồn tại',
  CANCELED_TICKET_SUCCESS: 'Hủy vé thành công!',
  GET_ORDER_FAILED: 'Lấy thông tin đơn hàng thất bại',
  GET_ORDER_DETAIL_FAILED: 'Lấy chi tiết đơn hàng thất bại',
  CANCELED_TICKET_FAILURE: 'Hủy vé thất bại',
  SESSION_TIME_IS_REQUIRED: 'Không được bỏ trống thời gian của phiên',
  SESSION_TIME_IS_MUST_BE_A_DATE: 'Thời gian phiên không đúng định dạng',
  BUS_ROUTE_IS_NOT_EXIST: 'Tuyến không tồn tại',
  BUS_ROUTE_IS_DEPARTURED: 'Tuyến đã khởi hành'
} as const

export const EVALUATE_MESSAGE = {
  VEHICLE_ID_IS_REQUIRED: 'Không được bỏ trống ID phương tiện',
  VEHICLE_ID_IS_MUST_BE_A_STRING: 'ID phương tiện phải là một chuỗi ký tự',
  VEHICLE_ID_IS_INVALID: 'ID phương tiện không đúng định dạng',
  VEHICLE_ID_IS_NOT_EXIST: 'ID phương tiện không tồn tại',
  VEHICLE_ID_IS_NOT_EXIST_IN_BILL: 'Bạn phải trải nghiệm phương tiện này mới có thể đánh giá',
  RATING_IS_REQUIRED: 'Không được bỏ trống xếp hạn đánh giá',
  RATING_IS_MUST_BE_A_NUMBER: 'Xếp hạn đánh giá phải là một số',
  RATING_IS_INVALID: 'Xếp hạn đánh giá không hợp lệ',
  CONTENT_IS_REQUIRED: 'Không được bỏ trống nội dung đánh giá',
  CONTENT_IS_MUST_BE_A_STRING: 'Nội dung đánh giá phải là một chuỗi ký tự',
  CONTENT_LENGTH_MUST_BE_FROM_1_TO_500: 'Nội dung đánh giá phải có độ dài từ 1 đến 500 ký tự',
  VEHICLE_ID_IS_ALREADY_EVALUATED: 'Bạn đã đánh giá phương tiện này rồi',
  CREATE_EVALUATE_SUCCESS: 'Gửi đánh giá thành công!',
  CREATE_EVALUATE_FAILURE: 'Gửi đánh giá thất bại',
  EVALUATE_ID_IS_REQUIRED: 'Không được bỏ trống ID đánh giá',
  EVALUATE_ID_IS_MUST_BE_A_STRING: 'ID đánh giá phải là một chuỗi ký tự',
  EVALUATE_ID_IS_INVALID: 'ID đánh giá không đúng định dạng',
  EVALUATE_ID_IS_NOT_EXIST: 'ID đánh giá không tồn tại hoặc bạn không có quyền thực hiện điều này',
  UPDATE_EVALUATE_SUCCESS: 'Cập nhật đánh giá thành công!',
  UPDATE_EVALUATE_FAILURE: 'Cập nhật đánh giá thất bại',
  DELETE_EVALUATE_SUCCESS: 'Xóa đánh giá thành công!',
  DELETE_EVALUATE_FAILURE: 'Xóa đánh giá thất bại',
  CURRENT_IS_REQUIRED: 'Không được bỏ trống số trang hiện tại',
  CURRENT_IS_MUST_BE_A_NUMBER: 'Số trang hiện tại phải là một số',
  CURRENT_IS_MUST_BE_GREATER_THAN_0: 'Số trang hiện tại phải lớn hơn 0',
  NO_MATCHING_RESULTS_FOUND: 'Không tìm thấy kết quả phù hợp',
  CREATE_EVALUATE_FEEDBACK_SUCCESS: 'Gửi phản hồi đánh giá thành công!',
  CREATE_EVALUATE_FEEDBACK_FAILURE: 'Gửi phản hồi đánh giá thất bại',
  EVALUATE_ID_IS_ALREADY_HAVE_FEEDBACK: 'Bạn đã gửi phản hồi cho đánh giá này rồi',
  EVALUATE_ID_IS_NOT_HAVE_FEEDBACK: 'Bạn chưa gửi phản hồi cho đánh giá này',
  UPDATE_EVALUATE_FEEDBACK_SUCCESS: 'Cập nhật phản hồi đánh giá thành công!',
  UPDATE_EVALUATE_FEEDBACK_FAILURE: 'Cập nhật phản hồi đánh giá thất bại',
  DELETE_EVALUATE_FEEDBACK_SUCCESS: 'Xóa phản hồi đánh giá thành công!',
  DELETE_EVALUATE_FEEDBACK_FAILURE: 'Xóa phản hồi đánh giá thất bại',
  GET_EVALUATE_FAILURE: 'Lấy thông tin đánh giá thất bại',
  SESSION_TIME_IS_REQUIRED: 'Không được bỏ trống thời gian của phiên',
  SESSION_TIME_IS_MUST_BE_A_DATE: 'Thời gian phiên không đúng định dạng'
} as const

export const BUSINESS_REGISTRATION_MESSAGE = {
  NAME_IS_REQUIRED: 'Không được bỏ trống tên doanh nghiệp',
  NAME_IS_MUST_BE_A_STRING: 'Tên doanh nghiệp phải là một chuỗi ký tự',
  NAME_LENGTH_MUST_BE_FROM_1_TO_50: 'Tên doanh nghiệp phải có độ dài từ 1 đến 50 ký tự',
  EMAIL_IS_REQUIRED: 'Không được bỏ trống email đăng ký doanh nghiệp',
  EMAIL_IS_MUST_BE_A_STRING: 'Email đăng ký doanh nghiệp phải là một chuỗi ký tự',
  EMAIL_LENGTH_MUST_BE_FROM_5_TO_100: 'Email đăng ký doanh nghiệp phải có độ dài từ 5 đến 100 ký tự',
  EMAIL_IS_INVALID: 'Email đăng ký doanh nghiệp không đúng định dạn',
  EMAIL_IS_ALWAYS_EXISTENT: 'Email đăng ký doanh nghiệp đã được sử dụng',
  PHONE_IS_REQUIRED: 'Số điện thoại đăng ký doanh nghiệp không được bỏ trống',
  PHONE_MUST_BE_A_STRING: 'Số điện thoại đăng ký doanh nghiệp phải là một chuỗi ký tự',
  PHONE_LENGTH_MUST_BE_FROM_10_TO_11: 'Số điện thoại đăng ký doanh nghiệp phải có độ dài từ 10 đến 11 ký tự',
  PHONE_IS_INVALID: 'Số điện thoại đăng ký doanh nghiệp không đúng định dạn',
  PHONE_IS_ALWAYS_EXISTENT: 'Số điện thoại đăng ký doanh nghiệp đã được sử dụng',
  HAVE_ACCOUNT_IS_REQUIRED: 'Không được bỏ trống câu trả lời cho câu hỏi có tài khoản không',
  HAVE_ACCOUNT_MUST_BE_A_BOOLEAN: 'Câu trả lời cho câu hỏi có tài khoản không phải có giá trị true hoặc false',
  REGISTER_SUCCESS: 'Đăng ký doanh nghiệp thành công!',
  BUSINESS_REGISTRATION_ID_IS_REQUIRED: 'Không được bỏ trống ID đăng ký doanh nghiệp',
  BUSINESS_REGISTRATION_ID_MUST_BE_A_STRING: 'ID đăng ký doanh nghiệp phải là một chuỗi ký tự',
  BUSINESS_REGISTRATION_ID_IS_NOT_EXISTENT: 'ID đăng ký doanh nghiệp không tồn tại',
  DECISION_IS_REQUIRED: 'Không được bỏ trống quyết định',
  DECISION_MUST_BE_A_BOOLEAN: 'Quyết định phải là true hoặc false',
  CENSOR_SUCCESS: 'Kiếm duyệt đăng ký doanh nghiệp thành công!',
  CENSOR_FAILED: 'Kiếm duyệt đăng ký doanh nghiệp thất bại',
  CURRENT_IS_REQUIRED: 'Không được bỏ trống số trang hiện tại',
  CURRENT_IS_MUST_BE_A_NUMBER: 'Số trang hiện tại phải là một số',
  CURRENT_IS_MUST_BE_GREATER_THAN_0: 'Số trang hiện tại phải lớn hơn 0',
  NO_MATCHING_RESULTS_FOUND: 'Không tìm thấy kết quả phù hợp',
  REGISTER_FAILED: 'Đăng ký doanh nghiệp thất bại',
  GET_BUSINESS_REGISTRATION__FAILED: 'Lấy thông tin đăng ký doanh nghiệp thất bại',
  SESSION_TIME_IS_REQUIRED: 'Không được bỏ trống thời gian của phiên',
  SESSION_TIME_IS_MUST_BE_A_DATE: 'Thời gian phiên không đúng định dạng'
} as const

export const NOTIFICATION_MESSAGE = {
  IMAGE_IS_REQUIRED: 'Bạn phải tải lên ít nhất 1 hình ảnh cho thông báo',
  TITLE_IS_REQUIRED: 'Không được bỏ trống tiên đều thông báo',
  TITLE_MUST_BE_STRING: 'Tiêu đề thông báo phải là một chuỗi ký tự',
  TITLE_LENGTH_MUST_BE_FROM_5_TO_200: 'Tiêu đề thông báo phải có độ dài từ 5 đến 200 ký tự',
  DESCRIPTION_IS_REQUIRED: 'Không được bỏ trống nội dung thông báo',
  DESCRIPTION_MUST_BE_STRING: 'Nội dung thông báo phải là một chuỗi ký tự',
  DESCRIPTION_LENGTH_MUST_BE_FROM_5_TO_2000: 'Nội dung thông báo phải có độ dài từ 5 đến 2000 ký tự',
  SET_NOTIFICATION_SUCCESS: 'Đặt thông báo thành công!',
  SET_NOTIFICATION_FAILED: 'Đặt thông báo thất bại',
  REMOVE_NOTIFICATION_SUCCESS: 'Xóa thông báo thành công!',
  REMOVE_NOTIFICATION_FAILED: 'Xóa thông báo thất bại',
  NOTIFICATION_NOT_FOUND: 'Không tìm thấy thông báo nào',
  GET_NOTIFICATION_FAILED: 'Lấy thông báo thất bại'
} as const

export const ACCOUNT_MANAGEMENT_MESSAGE = {
  CURRENT_IS_REQUIRED: 'Không được bỏ trống số trang hiện tại',
  CURRENT_IS_MUST_BE_A_NUMBER: 'Số trang hiện tại phải là một số',
  CURRENT_IS_MUST_BE_GREATER_THAN_0: 'Số trang hiện tại phải lớn hơn 0',
  GET_ACCOUNT_FAILURE: 'Lấy danh sách thông tin tài khoản thất bại',
  NO_MATCHING_RESULTS_FOUND: 'Không tìm thấy kết quả phù hợp',
  KEYWORDS_IS_REQUIRED: 'Không được bỏ trống từ khóa tìm kiếm',
  FIND_ACCOUNT_FAILURE: 'Tìm kiếm thông tin tài khoản thất bại',
  USER_ID_IS_REQUIRED: 'Không được bỏ trống ID người dùng',
  USER_ID_IS_INVALID: 'ID người dùng không hợp lệ',
  USER_ID_IS_NOT_EXIST: 'ID người dùng không tồn tại',
  REASON_IS_REQUIRED: 'Không được bỏ trống lý do khóa tài khoản',
  REASON_IS_MUST_BE_A_STRING: 'Lý do khóa tài khoản phải là một chuỗi ký tự',
  REASON_IS_MUST_BE_BETWEEN_1_AND_500_CHARACTERS: 'Lý do phải có độ dài từ 1 đến 500 ký tự',
  EXPIRED_AT_IS_REQUIRED: 'Không được bỏ trống thời gian hết hạn khóa tài khoản',
  EXPIRED_AT_IS_MUST_BE_A_VALID_DATE: 'Thời gian hết hạn khóa tài khoản phải là ngày hợp lệ',
  EXPIRED_AT_IS_MUST_BE_GREATER_THAN_CURRENT_DATE: 'Thời gian hết hạn khóa tài khoản phải muộn hơn ngày hiện tại',
  BAN_ACCOUNT_SUCCESS: 'Khóa tài khoản thành công!',
  BAN_ACCOUNT_FAILURE: 'Khóa tài khoản thất bại',
  USER_ID_IS_ALREADY_BANNED: 'Người dùng đã bị khóa tài khoản',
  USER_ID_IS_NOT_BANNED: 'Người dùng chưa bị khóa tài khoản',
  UNBAN_ACCOUNT_SUCCESS: 'Mở khóa tài khoản thành công!',
  UNBAN_ACCOUNT_FAILURE: 'Mở khóa tài khoản thất bại',
  MESSAGE_IS_REQUIRED: 'Không được bỏ trống tin nhắn',
  MESSAGE_IS_MUST_BE_A_STRING: 'Tin nhắn phải là một chuỗi ký tự',
  MESSAGE_IS_MUST_BE_BETWEEN_1_AND_500_CHARACTERS: 'Tin nhắn phải có độ dài từ 1 đến 500 ký tự',
  SEND_NOTIFICATIONS_SUCCESS: 'Gửi thông báo thành công!',
  SEND_NOTIFICATIONS_FAILURE: 'Gửi thông báo thất bại',
  SESSION_TIME_IS_REQUIRED: 'Không được bỏ trống thời gian của phiên',
  SESSION_TIME_IS_MUST_BE_A_DATE: 'Thời gian phiên không đúng định dạng'
} as const

export const STATISTICS_MESSAGE = {
  GET_STATISTICS_FAILURE: 'Lấy thông tin thống kê thất bại',
  START_TIME_IS_REQUIRED: 'Không được bỏ trống thời gian bắt đầu',
  START_TIME_IS_MUST_BE_A_VALID_DATE: 'Thời gian bắt đầu không hợp lệ',
  END_TIME_IS_REQUIRED: 'Không được bỏ trống thời gian kết thúc',
  END_TIME_IS_MUST_BE_A_VALID_DATE: 'Thời gian kết thúc không hợp lệ',
  END_TIME_IS_MUST_BE_GREATER_THAN_START_TIME: 'Thời gian kết thúc phải muộn hơn thời gian bắt đầu'
} as const

export const REVENUE_MESSAGE = {
  AMOUNT_REQUIRED: 'Không được bỏ trống số tiền',
  AMOUNT_MUST_BE_NUMBER: 'Số tiền phải là một số',
  AMOUNT_MUST_BE_GREATER_THAN_1000: 'Số tiền phải lớn hơn 1000',
  CREATE_BANK_ORDER_FAILURE: 'Tạo đơn hàng thanh toán ngân hàng thất bại',
  API_KEY_REQUIRED: 'Không được bỏ trống API Key',
  API_KEY_INVALID: 'API Key không hợp lệ',
  CHECKOUT_ORDER_SUCCESS: 'Thanh toán đơn hàng thành công!',
  CHECKOUT_ORDER_FAILURE: 'Thanh toán đơn hàng thất bại'
} as const
